export const artworks = [
  {
    title: "The Digital Horizon",
    tagline: "Where pixels meet perception",
    year: 2023,
    tag: "digital-art",
    link: "https://www.moma.org",
  },
  {
    title: "Neon Dreams",
    tagline: "Urban nights in fluorescent light",
    year: 2024,
    tag: "installation",
    link: "https://www.tate.org.uk",
  },
  {
    title: "Sustainable Futures",
    tagline: "Art from recycled materials",
    year: 2022,
    tag: "sculpture",
    link: "https://www.guggenheim.org",
  },
  {
    title: "Neural Canvas",
    tagline: "AI-generated masterpieces",
    year: 2024,
    tag: "ai-art",
    link: "https://www.sfmoma.org",
  },
  {
    title: "Quantum Reflections",
    tagline: "Physics meets art",
    year: 2023,
    tag: "mixed-media",
    link: "https://www.centrepompidou.fr",
  },
  {
    title: "Biomorphic Echoes",
    tagline: "Nature's patterns reimagined",
    year: 2024,
    tag: "organic-art",
    link: "https://www.whitney.org",
  },
  {
    title: "Virtual Vertigo",
    tagline: "Immersive VR experiences",
    year: 2023,
    tag: "virtual-reality",
    link: "https://www.palaisdetokyo.com",
  },
  {
    title: "Social Mirror",
    tagline: "Contemporary society reflected",
    year: 2024,
    tag: "conceptual",
    link: "https://www.newmuseum.org",
  },
];
